version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/heavenlyteam/easydb
    environment:
      TEST_RESULTS: /tmp/test-results # path to where test results will be save


    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: export GOFLAGS='-mod vendor'
      - run: export GO111MODULE=on
      - run:
          name: Download dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -v -race ./...